name: "Lint and Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint_and_test:
    name: Lint and run tests
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.1.6"

        - name: "Set up Python"
          uses: actions/setup-python@v5.1.0
          with:
            python-version: "3.11"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: Lint Check
          run:  ruff check custom_components

        - name: Format check
          run: ruff format --check custom_components

        - name: Run tests
          run: python -m pytest -v test
